### ISSUE TITLE
desc_add_url etc

### ISSUE THREAD

**Issue by hadley** [r-pkgs/desc#33]
Would be useful if `desc_add_url()` did not add duplicates, and returned TRUE/FALSE.

**Comment by gaborcsardi** [comment]
It does not add duplicates imo. (If it does, that's a bug.)

Functions that do not query a value return `self`. Why would you return TRUE/FALSE? If you add it, it will be added..... unless an error happens.

**Comment by hadley** [comment]
Return `TRUE`/`FALSE` is useful for usethis because then I can tell the user what's happened. It's not a big deal though

**Comment by gaborcsardi** [comment]
Yes, but what do they mean? TRUE if successful, FALSE if not? Why not throw an error in this case?

**Comment by hadley** [comment]
`TRUE` if the field has changed, `FALSE` otherwise. This is fairly specific to usethis, but I don't want to throw an error, because there may be other parts should still work (i.e. the goal of each `use_*` function is not to be atomic, but to deal with partially setup components)

**Comment by gaborcsardi** [comment]
I see. Thanks makes sense.

But I am reluctant to change it, since all other `set_` methods return `self`.... how about sg. like

```r
! identical(d$get_urls(), d$add_urls(new_url)$get_urls())
```

It is not super nice...

**Comment by hadley** [comment]
Yeah, lets not worry about it for desc. I've ended up with this general wrapper (not specifically for urls) in usethis:

```R

use_description_field <- function(name, value, base_path = ".", overwrite = FALSE) {
  path <- file.path(base_path, "DESCRIPTION")

  curr <- desc::desc_get(name, file = path)[[1]]
  if (identical(curr, value))
    return()

  if (is.na(curr) || overwrite) {
    message("* Setting DESCRIPTION ", name, " to '", value, "'.")
    desc::desc_set(name, value, file = path)
  } else {
    message("* Preserving existing field ", name)
  }
}
```
