### ISSUE TITLE
Depend on rprojroot?

### ISSUE THREAD

**Issue by hadley** [r-pkgs/desc#35]
desc would seem to be a natural home to replace the functionality previously found in `devtools::as.package()`, i.e. returning a DESCRIPTION file, looking in parent directories as necessary. Maybe `desc::package_desc()`? 

Alternatively, you could always call rprojroot, when given a directory as `file`.

**Comment by gaborcsardi** [comment]
Hmmm. Maybe the first options is less magical. `desc::package_desc()` can
just call `rprojroot` to get the root, and then read the file.

It would be nice to make it work with the non-oo api somehow, for quick
queries and updates.

**Comment by hadley** [comment]
One option would be to provide a sentinel class:

```R
package <- function(x) structure(x, class = "package")
is.package <- function(x) inherit(x, "package")
```

Then when looking at `file` you'd look to see if it's an existing file, an existing path, or a package (in which case you would look for the root).

**Comment by gaborcsardi** [comment]
Yeah, I like these in general, although I don't use them in `desc`. The `desc` like solution is to make the constructor even smarter, but I already hate how smart it is.....

So a sentinel class is good, it is a small change only. Adding the many `package_desc_*` functions is too much to maintain.

**Comment by hadley** [comment]
`desc::desc()$set(a = 1)$write()` isn't much more typing than `desc::desc_set(a = 1)`

**Comment by gaborcsardi** [comment]
Actually, you know what? I think it is OK to make the constructor a bit smarter. 

Currently, if there are no arguments, `description$new()` looks for `DESCRIPTION` in wd. If it is not there, it just fails. So it could use `rprojroot` by default, if `file` is a directory. That way, the current behavior does not change, and `desc::desc()` automatically finds `DESCRIPTION` in a package.

**Comment by gaborcsardi** [comment]
And also, all non-oo functions just work for packages as well....
