### ISSUE TITLE
backports dependency?

### ISSUE THREAD

**Issue by dpastoor** [r-pkgs/desc#37]
trying to install from github and ran into this error:

```
* installing *source* package 'desc' ...
** R
** inst
** tests
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'backports'
ERROR: lazy loading failed for package 'desc'
* removing 'C:/Program Files/R/R-3.3.2/library/desc'
* restoring previous 'C:/Program Files/R/R-3.3.2/library/desc'
Error: Command failed (1)
```

I looked for a backports import somewhere in the package and didn't see any so didn't know where the dependency was causing the failure.

Running

```
install.packages("backports")
```

resolved the issue.

**Comment by gaborcsardi** [comment]
`desc` does not need backports, probably one of its dependencies does.

**Comment by gaborcsardi** [comment]
Or maybe it is in the devtools toolchain somewhere? 

Nevertheless, a `sessionInfo()` output right after the error would help.

**Comment by dpastoor** [comment]
fresh R install on Windows 10

```
Session info ------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, mingw32             
 ui       RStudio (1.0.44)            
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            
 date     2016-11-30                  

Packages ----------------------------------------------------------------------------------------------------------------------
 package  * version date       source        
 devtools   1.12.0  2016-06-24 CRAN (R 3.3.2)
 digest     0.6.10  2016-08-02 CRAN (R 3.3.2)
 memoise    1.0.0   2016-01-29 CRAN (R 3.3.2)
 withr      1.0.2   2016-06-20 CRAN (R 3.3.2)
```

Sorry I wasn't completely clear above - from a fresh R install (only installed devtools) I was installing usethis, and when it got to the desc installation it errored with the above missing dep error.

```
devtools::install_github("r-pkgs/usethis")
```

When I manually installed backports and then reinstalled, everything installed properly

**Comment by gaborcsardi** [comment]
OK, I think this is a `pkgload` or `devtools` bug, probably. `desc` uses `rprojroot`, which uses `backports`, but it does not get installed automatically.

I'll move this issue to the appropriate repo, once I find out where that is.

**Comment by gaborcsardi** [comment]
Here is the `devtools` bug report: https://github.com/hadley/devtools/issues/1409
