### ISSUE TITLE
Multiple Remotes fields

### ISSUE THREAD

**Issue by jimhester** [r-pkgs/desc#43]
This is a continuation of https://github.com/hadley/devtools/issues/1342 and https://github.com/r-pkgs/pkgload/issues/20, basically what happens if there are multiple `Remotes:` fields specified.

**Comment by gaborcsardi** [comment]
I am pretty sure that is not valid and/or does not work properly with base R tools.

**Comment by jimhester** [comment]
Here is a simple reprex, I guess the question is whether we want the default behavior of `read.dcf()` which is the current desc behavior, the behavior with `all = TRUE`, or an error.

```r
writeLines(c("Package: xyz", "Remotes: foo", "Remotes: bar"), "test")
desc::desc("test")
#> Package: xyz
#> Remotes: Remotes: bar

read.dcf("test")
#>     Package Remotes
#> [1,] "xyz"   "bar"

read.dcf("test", all = TRUE)
#>  Package  Remotes
#> 1     xyz foo, bar
```

**Comment by gaborcsardi** [comment]
Bug. I did not anticipate duplicates.

**Comment by gaborcsardi** [comment]
I would say an error is most sensible, because these files are broken, after all.

**Comment by gaborcsardi** [comment]
`read.dcf` either ignores duplicates (used the last one), or merges them, so there is no straightforward way to detect duplicates.

My idea is to parse twice, with and without `all = TRUE`, and compare. Hopefully it'll only have differences if duplicates exist.
